{% set name = "openapi-spec-validator" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/p1c2u/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 331acbcefe9a77cfeca81a6fae776258d3db0071b4d4be9238d0764e3e6b9d3e

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - openapi-spec-validator = openapi_spec_validator.__main__:main

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - jsonschema >=4.18.0,<5.0.0
    - openapi-schema-validator >=0.6.0,<0.7.0
    - importlib-resources >=5.8,<7.0  # [py<39]
    - jsonschema-path >=0.3.1,<0.4.0
    - lazy-object-proxy >=1.7.1,<2.0.0

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - requests
  imports:
    - openapi_spec_validator
  commands:
    - pip check
    - pytest -vv
    - openapi-spec-validator --help

about:
  home: https://github.com/p1c2u/openapi-spec-validator
  license: Apache-2.0
  summary: OpenAPI 2.0 (aka Swagger) and OpenAPI 3 spec validator
  license_family: APACHE
  license_file: LICENSE
  description: |-
    OpenAPI Spec Validator is a Python library that validates OpenAPI Specs
    against the OpenAPI 2.0 (aka Swagger) and OpenAPI 3.0 specification. The
    validator aims to check for full compliance with the Specification.
  dev_url: https://github.com/p1c2u/openapi-spec-validator
  doc_url: https://openapi-spec-validator.readthedocs.io

extra:
  recipe-maintainers:
    - rvalieris
